name: learn-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install -g bats
      - run: bats -v
      - run: echo $YOLO
        env:
          YOLO: ${{ env.YOLOVAR }}
      - run: echo ${{ env.ACT }}
      - run: echo ${{ secrets.TEST }}
      - env:
          testsecret: ${{ secrets.TEST }}
        run: echo $testsecret
